In [12]:
!wget --inet4-only https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-10-28 14:02:47--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.2’

input.txt.2         100%[===================>]   1.06M  3.06MB/s    in 0.3s    

2024-10-28 14:02:48 (3.06 MB/s) - ‘input.txt.2’ saved [1115394/1115394]



In [13]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [14]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [15]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [16]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [17]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [18]:
import torch
data =  torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [19]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [20]:
block_size = 8
train_data[:block_size+1]


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [21]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when in put is {context} output is: {target}")


when in put is tensor([18]) output is: 47
when in put is tensor([18, 47]) output is: 56
when in put is tensor([18, 47, 56]) output is: 57
when in put is tensor([18, 47, 56, 57]) output is: 58
when in put is tensor([18, 47, 56, 57, 58]) output is: 1
when in put is tensor([18, 47, 56, 57, 58,  1]) output is: 15
when in put is tensor([18, 47, 56, 57, 58,  1, 15]) output is: 47
when in put is tensor([18, 47, 56, 57, 58,  1, 15, 47]) output is: 58


In [22]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

n_embd = 32
head_size = 16

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix]) 
    return x,y

xb, yb = get_batch("train")
print("inputs:")
print(xb.shape)
print(xb)
print("targets:")
print(yb.shape)
print(yb)

print ("---------")

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when input is {context.tolist()} target is: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
---------
when input is [24] target is: 43
when input is [24, 43] target is: 58
when input is [24, 43, 58] target is: 5
when input is [24, 43, 58, 5] target is: 57
when input is [24, 43, 58, 5, 57] target is: 1
when input is [24, 43, 58, 5, 57, 1] target is: 46
when input is [24, 43, 58, 5, 57, 1, 46] target is: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] target is: 39
when input is [44] target is: 53
when input is [44, 53] target is: 56
when input is [44, 53, 56] target is: 1
when input is [44, 53, 56, 1] target is: 58
when input is [44, 53, 56, 1, 58] target is: 46
when input is [44, 53, 56, 1,

In [31]:
import torch
import torch.nn as nn
from torch.nn import functional as F 


class Head(nn.Module):

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.value(x)

        wei = q @ k.transpose(-2, -1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf"))
        wei = F.softmax(wei, dim=-1)

        v = self.value(x)
        out = wei @ v
        return out



class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.positional_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = Head(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)
    

    def forward(self, idx, targets=None):
       
        B, T = idx.shape
        token_emb = self.token_embedding_table(idx)
        pos_emb = self.positional_embedding_table(torch.arange(T))
        x = token_emb + pos_emb
        x = self.sa_head(x)
        logits = self.lm_head(x)
        loss = None
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
         
        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
        


m = BigramLanguageModel()
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

idx = torch.zeros((1,1), dtype=torch.long)
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))



torch.Size([32, 65])
tensor(4.1387, grad_fn=<NllLossBackward0>)

SvZBKP&';
-T.
;pgFaRoFAmsQ:,iIOQMxbR;jbufZdDG$QBtK-rxOfDeoMCtVtFsXTbHRBoQ'fFW;?jij:glhz&!UjAqDs,ul?u


In [32]:
optimiser = torch.optim.AdamW(m.parameters(), lr=1e-3)


In [34]:
eval_intervals = 500

@torch.no_grad
def estimate_loss():
    out = {}
    m.eval()
    for split in ["train", "val"]:
        losses = torch.zeros(eval_intervals)
        for k in range(eval_intervals):
            X, Y = get_batch(split)
            logits, loss = m(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    m.train()
    return out


In [35]:
batch_size = 32
for iter in range(10000):

    if iter % eval_intervals == 0:
        losses = estimate_loss()
        print(f"step : {iter}, train loss: {losses['train']:.4f}, val loss: {losses['val']:.4f}")

    xb, yb = get_batch("train")
    logits, loss = m(xb, yb)
    optimiser.zero_grad(set_to_none=True)
    loss.backward()
    optimiser.step()
print(loss.item())

    

step : 0, train loss: 4.2362, val loss: 4.2411
step : 500, train loss: 2.8350, val loss: 2.8501
step : 1000, train loss: 2.5521, val loss: 2.5560
step : 1500, train loss: 2.4890, val loss: 2.4965
step : 2000, train loss: 2.4673, val loss: 2.4654
step : 2500, train loss: 2.4455, val loss: 2.4596
step : 3000, train loss: 2.4373, val loss: 2.4355
step : 3500, train loss: 2.4157, val loss: 2.4282
step : 4000, train loss: 2.4120, val loss: 2.4109
step : 4500, train loss: 2.4000, val loss: 2.4115
step : 5000, train loss: 2.3890, val loss: 2.4131
step : 5500, train loss: 2.3812, val loss: 2.4123
step : 6000, train loss: 2.3886, val loss: 2.4042
step : 6500, train loss: 2.3787, val loss: 2.4028
step : 7000, train loss: 2.3749, val loss: 2.3967
step : 7500, train loss: 2.3740, val loss: 2.3980
step : 8000, train loss: 2.3801, val loss: 2.3946
step : 8500, train loss: 2.3648, val loss: 2.3891
step : 9000, train loss: 2.3654, val loss: 2.3861
step : 9500, train loss: 2.3642, val loss: 2.3828
2.25

In [36]:
idx = torch.zeros((1,1), dtype=torch.long)
print(decode(m.generate(idx, max_new_tokens=500)[0].tolist()))



D tsecame ucke,
Cincke ourry a hetimurns alel.
CUFRLARET:
Wh whoby, heand smy frer thou cI IS helat and bthir: yo-wor sheet tan to
we wador us nday, wes rsape ont hpp, fo onoung pan:
I min acen, incough blay 's whal tue asu, int tharveve to que ouge tift hainfe; nofra equeintito of higus he ogh hay cer hashaldeecen we,
Nne ye!:
Th
Wheend shed swet bey chot fto mam::
Gothberporvaty nd omre is ist hou eptoe ure paingafis hy G yovighe hy gios the'ld smurs, ghre.

RTourner
S:
RDAnut thamakis theanki
